// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/v1/alerts.proto

package alertv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // Identificador de quem pediu
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                                // Ex: Par crypto - ex: "BTC/EUR"
	TargetPrice   float64                `protobuf:"fixed64,3,opt,name=target_price,json=targetPrice,proto3" json:"target_price,omitempty"` // Preço alvo/ Alerta
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRequest) Reset() {
	*x = CreateAlertRequest{}
	mi := &file_api_proto_v1_alerts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRequest) ProtoMessage() {}

func (x *CreateAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_alerts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAlertRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAlertRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateAlertRequest) GetTargetPrice() float64 {
	if x != nil {
		return x.TargetPrice
	}
	return 0
}

type CreateAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertResponse) Reset() {
	*x = CreateAlertResponse{}
	mi := &file_api_proto_v1_alerts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertResponse) ProtoMessage() {}

func (x *CreateAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_alerts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_alerts_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAlertResponse) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *CreateAlertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateAlertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_v1_alerts_proto protoreflect.FileDescriptor

const file_api_proto_v1_alerts_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/alerts.proto\x12\fapi.proto.v1\"h\n" +
	"\x12CreateAlertRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12!\n" +
	"\ftarget_price\x18\x03 \x01(\x01R\vtargetPrice\"d\n" +
	"\x13CreateAlertResponse\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2b\n" +
	"\fAlertService\x12R\n" +
	"\vCreateAlert\x12 .api.proto.v1.CreateAlertRequest\x1a!.api.proto.v1.CreateAlertResponseB*Z(cryptotracker/alert/api/proto/v1;alertv1b\x06proto3"

var (
	file_api_proto_v1_alerts_proto_rawDescOnce sync.Once
	file_api_proto_v1_alerts_proto_rawDescData []byte
)

func file_api_proto_v1_alerts_proto_rawDescGZIP() []byte {
	file_api_proto_v1_alerts_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_alerts_proto_rawDesc), len(file_api_proto_v1_alerts_proto_rawDesc)))
	})
	return file_api_proto_v1_alerts_proto_rawDescData
}

var file_api_proto_v1_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_alerts_proto_goTypes = []any{
	(*CreateAlertRequest)(nil),  // 0: api.proto.v1.CreateAlertRequest
	(*CreateAlertResponse)(nil), // 1: api.proto.v1.CreateAlertResponse
}
var file_api_proto_v1_alerts_proto_depIdxs = []int32{
	0, // 0: api.proto.v1.AlertService.CreateAlert:input_type -> api.proto.v1.CreateAlertRequest
	1, // 1: api.proto.v1.AlertService.CreateAlert:output_type -> api.proto.v1.CreateAlertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_alerts_proto_init() }
func file_api_proto_v1_alerts_proto_init() {
	if File_api_proto_v1_alerts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_alerts_proto_rawDesc), len(file_api_proto_v1_alerts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_alerts_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_alerts_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_alerts_proto_msgTypes,
	}.Build()
	File_api_proto_v1_alerts_proto = out.File
	file_api_proto_v1_alerts_proto_goTypes = nil
	file_api_proto_v1_alerts_proto_depIdxs = nil
}
